### ISSUE TITLE
how to deploy another OHIF dicom viewer or change the address of OHIF?

### ISSUE THREAD

**Issue by aloux00** [DICOMcloud/DICOMweb-js#11]

**Comment by Zaid-Safadi** [comment]
@aloux00, here is the line where you can change the URL of the viewer:
https://github.com/DICOMcloud/DICOMweb-js/blob/master/Demo/Web.config#L17

As for deploying another version of the OHIF dicom viewer. I'd recommend you take a look at the OHIF docs for instructions. Here is a link for building the standalone version of the OHIF viewer:
https://docs.ohif.org/standalone-viewer/usage.html
