### ISSUE TITLE
Uploading large .DCM files to server does not work

### ISSUE THREAD

**Issue by wi55em** [DICOMcloud/DICOMweb-js#12]
Hi @Zaid-Safadi, 

I don't know if there is still support on this app but here's my issue.

I have my server working on localhost:44301 and have no issues uploading small files (in terms of size) and even have a Standalone OHIF Viewer connected to my server and I can verify that my uploadings are working fine. 

But for now, trying to upload a 700MB single .DCM file is not working and gives me the following error. 

![image](https://user-images.githubusercontent.com/35816694/59793075-a78ef800-92a3-11e9-83f5-00c3643ce189.png)

If there is any way I can do to make a large uploading possible ?

**Comment by wi55em** [comment]
I would add that even when I have changed the web config in my DICOMCloud app to accept files as large as 1GB, I still get that error shown above.

![image](https://user-images.githubusercontent.com/35816694/59795552-7e716600-92a9-11e9-8869-b537eea9824d.png)

**Comment by wi55em** [comment]
This website includes many free .DCM files ready to download: http://www.dclunie.com/pixelmedimagearchive/upmcdigitalmammotomocollection/index.html

Uploadings of...
- 100MB DCM files succeeded. 
- 500MB DCM files crashed. 

Note: With 7-Zip on Windows I was able to unzip the folders and use the dicom files.

**Comment by Zaid-Safadi** [comment]
@wi55em this is a .NET upload size issue. There are two configuration in the web.config that needs to be updated and each has different unit that you should be mindful of:

- `maxRequestLength` is measured in kilobytes
- `maxAllowedContentLength` is measured in bytes

https://stackoverflow.com/questions/3853767/maximum-request-length-exceeded/

**Comment by wi55em** [comment]
@Zaid-Safadi Thanks Zaid for your reply. 

I had a look over these configurations, but at this point I think that my error is caused because we are trying to store the image with a bytearray. And bytearrays require that the memory inside it is contiguous which makes the browser crash if it does not have access to enough contiguous memory in the RAM.
