### ISSUE TITLE
to convert DICOM image to .jpeg image.

### ISSUE THREAD

**Issue by jagjotwadali** [DICOMcloud/DICOMweb-js#4]
Hi @Zaid-Safadi .
I need a help .

I want to show DICOM image in thumbnail size on the web page .I thought to convert a dicom image to jpeg  and then display it 
Can you help in that.

**Comment by Zaid-Safadi** [comment]
What library are you using in your application to read the dicom file? As long as the library can decode the image you can use .NET GDI+ to resize and create your thumbnail

**Comment by jagjotwadali** [comment]
Currently I am using DWV dicom viewer to display the JPEG and DICOM images in that.

But before that I want to display the uploaded DICOM images on the webpage in thumbnail .In order to do that the option is to convert DICOM to JPEG.

I am trying different codes but I didnt find the right one.

**Comment by Zaid-Safadi** [comment]
You can use a server side library to decode the DICOM image and convert it into JPEG. Take a look at this .NET library which supports almost all DICOM transfer syntax: https://github.com/fo-dicom/fo-dicom
