### ISSUE TITLE
Multi-file upload not working

### ISSUE THREAD

**Issue by knopkem** [DICOMcloud/DICOMweb-js#6]
When trying to upload multiple files at once, only 1 file ends up on the server. The multipart/related request also shows only the first file in the payload. Can you reproduce?

**Comment by Zaid-Safadi** [comment]
Thank you for reporting this @knopkem 
Are you using the demo file upload to test this?

I see the file upload is allowing multiple files to be selected although I Initially intended to only allow 1 file to be uploaded in the code [Line 67](https://github.com/DICOMcloud/DICOMweb-js/blob/master/Demo/JSLib/Store/StoreView.ts) (as I didn't want heavy load on the online server).

I'll look into this and probably apply a soft-limit only on the online demo to allow 1 or 2 files but can be turned off in configuration to allow uploading multiple files.

Would this fix your issue?

**Comment by knopkem** [comment]
yes, I tested with the demo file upload only and like you said it looks like multifile selection is possible but than only one file is sent. 

A softlimit on the online demo with a config option to disable this on a local build would be great, thanks.

**Comment by Zaid-Safadi** [comment]
@knopkem this is fixed now. I've set a soft limit of 4 files. This setting can be changed from the web.config by either removing the entry from the appSettings, or setting it to a value less than 1:
`<add key="app:maxUpload" value="4"/>`

Also, if you are using the DICOMcloud server, I've fixed two related issues, you can view them here [issue 16](https://github.com/DICOMcloud/DICOMcloud/issues/16) and [issue 15](https://github.com/DICOMcloud/DICOMcloud/issues/15)
