### ISSUE TITLE
includefield not handled properly

### ISSUE THREAD

**Issue by knopkem** [DICOMcloud/DICOMweb-js#7]
From my interpretation of PS3.18:

`includefield={attributeID} | all​
0-n includefield / {attributeID} pairs allowed`
to include multiple attributes the query needs to always repeat includefield, however dicomweb-js seems to concatenate multiple tags.  also see the give example on page 76:

> http://dicomrs/studies?PatientID=11235813&includefield=00081048&includefield=00081049&includefield=00081060​

**Comment by knopkem** [comment]
You are right dicomweb-js is handling it correctly, I just tested with the latest demo. I was testing the client against another wado server which must have merged the duplicated parameters. Sorry for the noise. Great project by the way, thanks for making it public.

**Comment by Zaid-Safadi** [comment]
no worries. glad it is working as expected @knopkem 
Are you able to share the name of the wado server you are testing with? I like to test with other servers to ensure compliance of my code.

**Comment by Zaid-Safadi** [comment]
no worries. glad it is working as expected @knopkem 
Are you able to share the name of the wado server you are testing with? I like to test with other servers to ensure compliance of my code.

**Comment by knopkem** [comment]
The wado-server I was referring to is an inhouse project of the company I'm working for (sorry). So far they work pretty well together, I'll let you know if I find any issues.
The only other available wado-servers I could find are: orthanc, dcm4chee-arc-light and leadtools (trial), I'm sure you already know all these. It would be great if we could share more resources. Maybe this would be a good place to post to: https://github.com/chafey/dicomWeb

**Comment by knopkem** [comment]
The wado-server I was referring to is an inhouse project of the company I'm working for (sorry). So far they work pretty well together, I'll let you know if I find any issues.
The only other available wado-servers I could find are: orthanc, dcm4chee-arc-light and leadtools (trial), I'm sure you already know all these. It would be great if we could share more resources. Maybe this would be a good place to post to: https://github.com/chafey/dicomWeb

**Comment by knopkem** [comment]
The wado-server I was referring to is an inhouse project of the company I'm working for (sorry). So far they work pretty well together, I'll let you know if I find any issues.
The only other available wado-servers I could find are: orthanc, dcm4chee-arc-light and leadtools (trial), I'm sure you already know all these. It would be great if we could share more resources. Maybe this would be a good place to post to: https://github.com/chafey/dicomWeb
